name: lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and run pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        
        set +e
        pre-commit run --all-files || true
        git --no-pager diff  # Show differences from pre-commit
        set -e

       
